/**
 * Seed geometry for the private rooms: each room's door zone + seat coordinates,
 * written into Postgres by `seed.ts`. These MIRROR the generated campus geometry
 * (door zones and seats the campus generator authors for rooms 1-6). The manifest
 * (`@metaverse/shared` `geometryManifestSchema`, generated by `gen_campus.py`) is
 * the authoritative source; `backend/test/geometry.test.ts` cross-checks every
 * value here against it, so a re-authored campus that drifts from this table
 * fails CI.
 *
 * Coordinate note: seats here are TILE-CENTRE pixels (the map object layer stores
 * a seat's top-left corner, and the DB stores the centre) — so each seat equals
 * the manifest seat plus half a tile on both axes. Door zones match the manifest
 * exactly. The cross-check test encodes both relationships.
 *
 * Pure data, no imports, so the cross-check runs service-free.
 */
export interface SeedSeat {
  id: number;
  x: number;
  y: number;
  facing: "down" | "left" | "right" | "up";
}

export interface SeedRoom {
  id: string;
  doorZone: { x: number; y: number; width: number; height: number };
  seats: readonly SeedSeat[];
}

export const rooms: readonly SeedRoom[] = [
  // Hostel wing rooms (map: campus.json south, PRD 13). Capacities 5/8/12 — seat
  // ids/coords mirror the seats objectgroup the generator authors for rooms 1-3.
  {
    id: "1",
    doorZone: { x: 720, y: 1600, width: 32, height: 16 },
    seats: [
      { id: 0, x: 712, y: 1640, facing: "down" }, { id: 1, x: 744, y: 1640, facing: "down" }, { id: 2, x: 776, y: 1640, facing: "down" }, { id: 3, x: 728, y: 1704, facing: "up" }, { id: 4, x: 760, y: 1704, facing: "up" }
    ]
  },
  {
    id: "2",
    doorZone: { x: 512, y: 1600, width: 32, height: 16 },
    seats: [
      { id: 0, x: 488, y: 1640, facing: "down" }, { id: 1, x: 520, y: 1640, facing: "down" }, { id: 2, x: 552, y: 1640, facing: "down" }, { id: 3, x: 584, y: 1640, facing: "down" }, { id: 4, x: 488, y: 1704, facing: "up" }, { id: 5, x: 520, y: 1704, facing: "up" }, { id: 6, x: 552, y: 1704, facing: "up" }, { id: 7, x: 584, y: 1704, facing: "up" }
    ]
  },
  {
    id: "3",
    doorZone: { x: 272, y: 1600, width: 32, height: 16 },
    seats: [
      { id: 0, x: 216, y: 1656, facing: "down" }, { id: 1, x: 248, y: 1656, facing: "down" }, { id: 2, x: 280, y: 1656, facing: "down" }, { id: 3, x: 312, y: 1656, facing: "down" }, { id: 4, x: 344, y: 1656, facing: "down" }, { id: 5, x: 376, y: 1656, facing: "down" }, { id: 6, x: 216, y: 1720, facing: "up" }, { id: 7, x: 248, y: 1720, facing: "up" }, { id: 8, x: 280, y: 1720, facing: "up" }, { id: 9, x: 312, y: 1720, facing: "up" }, { id: 10, x: 344, y: 1720, facing: "up" }, { id: 11, x: 376, y: 1720, facing: "up" }
    ]
  },
  // Campus HQ rooms (map: campus.json, 120×90 tiles, 16px/tile)
  {
    id: "4",
    doorZone: { x: 576, y: 176, width: 32, height: 16 },
    seats: [
      { id: 0, x: 568, y: 104, facing: "right" }, { id: 1, x: 632, y: 104, facing: "left" },
      { id: 2, x: 600, y:  72, facing: "down"  }, { id: 3, x: 600, y: 136, facing: "up"   }
    ]
  },
  {
    id: "5",
    doorZone: { x: 784, y: 176, width: 32, height: 16 },
    seats: [
      { id: 0, x: 776, y: 104, facing: "right" }, { id: 1, x: 840, y: 104, facing: "left" },
      { id: 2, x: 808, y:  72, facing: "down"  }, { id: 3, x: 808, y: 136, facing: "up"   }
    ]
  },
  {
    id: "6",
    doorZone: { x: 1008, y: 176, width: 32, height: 16 },
    seats: [
      { id: 0, x: 1000, y: 104, facing: "right" }, { id: 1, x: 1064, y: 104, facing: "left" },
      { id: 2, x: 1032, y:  72, facing: "down"  }, { id: 3, x: 1032, y: 136, facing: "up"   }
    ]
  }
] as const;
