/**
 * Snake sprite-tile selection — pure, no DOM/Phaser/net.
 *
 * The renderer draws the snake from a 16-tile sprite sheet
 * (`public/assets/arcade/snake_tiles.png`, generated by
 * `frontend/scripts/gen_snake_sprites.py`) instead of flat rectangles (issue
 * #163). Deciding WHICH tile a segment uses is geometry, not drawing, so it
 * lives here with its own tests; the renderer just blits the returned index.
 *
 * Sheet layout — one row of 16 tiles, 16×16 px each, left to right:
 *   0 head→right  1 head→down  2 head→left  3 head→up
 *   4 body horizontal          5 body vertical
 *   6 bend up+right  7 bend right+down  8 bend down+left  9 bend left+up
 *  10 tail→right  11 tail→down  12 tail→left  13 tail→up   (arrow = toward head)
 *  14 food (apple)            15 wall block
 */
import type { Cell, Dir } from "./snake";

export const SNAKE_TILE_PX = 16;
export const SNAKE_TILE_COUNT = 16;
export const SNAKE_SHEET_URL = "/assets/arcade/snake_tiles.png";

export const FOOD_TILE = 14;
export const WALL_TILE = 15;

const HEAD_TILE: Record<Dir, number> = { right: 0, down: 1, left: 2, up: 3 };
const TAIL_TILE: Record<Dir, number> = { right: 10, down: 11, left: 12, up: 13 };
const STRAIGHT_TILE = { horizontal: 4, vertical: 5 } as const;

/** Bend tile by the pair of edges the segment connects, in canonical order. */
const BEND_TILE: Record<string, number> = {
  "up|right": 6,
  "right|down": 7,
  "down|left": 8,
  "left|up": 9,
};

/**
 * Step direction from `from` to the adjacent cell `to`, or null when the cells
 * are not orthogonally adjacent (defensive — the reducer never produces that).
 */
export function dirBetween(from: Cell, to: Cell): Dir | null {
  const dx = to.x - from.x;
  const dy = to.y - from.y;
  if (dx === 1 && dy === 0) return "right";
  if (dx === -1 && dy === 0) return "left";
  if (dx === 0 && dy === 1) return "down";
  if (dx === 0 && dy === -1) return "up";
  return null;
}

function bendKey(a: Dir, b: Dir): string {
  const order: Dir[] = ["up", "right", "down", "left"];
  const [first, second] = order.indexOf(a) <= order.indexOf(b) ? [a, b] : [b, a];
  const key = `${first}|${second}`;
  // "up|left" is the same corner as "left|up"; canonicalise to the table's key.
  return key === "up|left" ? "left|up" : key;
}

/**
 * Tile index for body segment `i` (0 = head). `dir` is the direction the head
 * last moved, used for a length-1 snake and as the head's facing.
 */
export function snakeTileIndex(body: readonly Cell[], i: number, dir: Dir): number {
  const n = body.length;
  const cell = body[i];
  if (!cell) return STRAIGHT_TILE.horizontal;

  if (i === 0) {
    const next = body[1];
    const facing = next ? dirBetween(next, cell) ?? dir : dir;
    return HEAD_TILE[facing];
  }

  if (i === n - 1) {
    const prev = body[i - 1];
    const facing = prev ? dirBetween(cell, prev) ?? dir : dir;
    return TAIL_TILE[facing];
  }

  const prev = body[i - 1];
  const next = body[i + 1];
  if (!prev || !next) return STRAIGHT_TILE.horizontal;
  const toHead = dirBetween(cell, prev);
  const toTail = dirBetween(cell, next);
  if (!toHead || !toTail) return STRAIGHT_TILE.horizontal;

  if (toHead === "left" || toHead === "right") {
    if (toTail === "left" || toTail === "right") return STRAIGHT_TILE.horizontal;
  } else if (toTail === "up" || toTail === "down") {
    return STRAIGHT_TILE.vertical;
  }
  return BEND_TILE[bendKey(toHead, toTail)] ?? STRAIGHT_TILE.horizontal;
}
