/**
 * Framework-free constants shared by the backend (runtime validation + enforcement)
 * and the frontend (UI limits + event wiring). This module imports nothing — in
 * particular no zod — so consumers can pull event names and limits without dragging
 * the schema/runtime cost into their bundle.
 */
import type { BoardGame } from "./games/board.js";

/** Movement / facing directions. Order is significant only as a stable list. */
export const DIRS = ["down", "left", "right", "up"] as const;

/**
 * Schema version of the generated server geometry manifest
 * (`campus.geometry.json`, emitted by `frontend/scripts/gen_campus.py`). The
 * backend loads the manifest, `safeParse`s it against `geometryManifestSchema`,
 * and refuses to become ready when the on-disk `version` does not equal this
 * constant — so a manifest generated by an older/newer generator can never be
 * silently trusted. Bump this (and the `GEOMETRY_MANIFEST_VERSION` literal in
 * `gen_campus.py`) together whenever the manifest shape changes.
 */
export const GEOMETRY_MANIFEST_VERSION = 1;

/**
 * Canonical arcade-cabinet game ids. The high-score REST resource validates a
 * submitted `game` against this tuple, and the frontend keys its cabinets and
 * leaderboards off the same list — single source of truth for both sides.
 */
export const ARCADE_GAMES = ["snake", "flappy"] as const;
export type ArcadeGame = (typeof ARCADE_GAMES)[number];

/**
 * Board-game tables (PRD 11 phase 2). Each table is a two-seat, server-
 * authoritative match of one board game. This registry is the single source of
 * truth for which tables exist and which game each runs: the campus map authors
 * seats/props against these ids, the backend validates `tableId`/`game`, and the
 * frontend renders the board by looking the id up here. `maps.test.ts` cross-
 * checks the generated map against this list.
 */
export const BOARD_TABLE_IDS = ["ttt-1", "c4-1"] as const;
export type BoardTableId = (typeof BOARD_TABLE_IDS)[number];

export const BOARD_TABLES: readonly { id: BoardTableId; game: BoardGame }[] = [
  { id: "ttt-1", game: "tictactoe" },
  { id: "c4-1", game: "connect4" },
];

/** The board game a given table runs, or undefined for an unknown id. */
export function gameForTable(tableId: string): BoardGame | undefined {
  return BOARD_TABLES.find((t) => t.id === tableId)?.game;
}

/** Human-readable name per board game (labels for HUD + the presence read model). */
export const BOARD_GAME_LABELS: Record<BoardGame, string> = {
  tictactoe: "Tic-Tac-Toe",
  connect4: "Connect Four",
};

/** Display label for a board table (its game's name), or the id for an unknown table. */
export function boardTableLabel(tableId: string): string {
  const game = gameForTable(tableId);
  return game ? BOARD_GAME_LABELS[game] : tableId;
}

/** Phases of a board-table match, as seen on the wire. */
export const BOARD_MATCH_PHASES = ["waiting", "offer", "active", "over"] as const;
export type BoardMatchPhase = (typeof BOARD_MATCH_PHASES)[number];

/** How a board match ended. */
export const BOARD_END_REASONS = ["win", "draw", "forfeit"] as const;
export type BoardEndReason = (typeof BOARD_END_REASONS)[number];

/** Reasons the server rejects a board action (typed error to the client). */
export const BOARD_MOVE_REJECTIONS = [
  "not-seated",
  "not-your-turn",
  "illegal-move",
  "no-match",
  "seat-taken",
] as const;
export type BoardMoveRejection = (typeof BOARD_MOVE_REJECTIONS)[number];

/** TTL (seconds) on the Redis snapshot of a live board match. */
export const BOARD_MATCH_TTL_SECONDS = 8 * 60 * 60;

/** Chat channel scopes a client may request. */
export const CHAT_SCOPES = ["world", "room"] as const;

/**
 * Named campus areas (PRD 20). The single source of truth for human-readable
 * place names, consumed by the HUD map labels here and by in-world signage in
 * PRD 22. `rooms` lists the private-room ids an area groups (the two hostels);
 * areas without `rooms` (Stage, Game Arcade) are located from map geometry. This
 * is a constants addition — no wire-shape change.
 */
export interface AreaName {
  /** Stable area key (used to resolve a display name from map-derived rects). */
  readonly id: string;
  /** Human-readable label shown on the map (and future world signage). */
  readonly name: string;
  /** Private-room ids grouped under this area, if room-based. */
  readonly rooms?: readonly string[];
}

export const AREA_NAMES: readonly AreaName[] = [
  { id: "mandakini", name: "Mandakini Hostel", rooms: ["1", "2", "3"] },
  { id: "cauvery", name: "Cauvery Hostel", rooms: ["4", "5", "6"] },
  { id: "stage", name: "Stage" },
  { id: "arcade", name: "Game Arcade" },
] as const;

/** Display name for an area id, or undefined for an unknown id. */
export function areaNameForId(id: string): string | undefined {
  return AREA_NAMES.find((a) => a.id === id)?.name;
}

/** The area name a given private-room id belongs to, or undefined. */
export function areaNameForRoom(roomId: string): string | undefined {
  return AREA_NAMES.find((a) => a.rooms?.includes(roomId))?.name;
}

/**
 * The area *id* a given private-room id belongs to, or undefined. Collapses a
 * room id (e.g. "1") onto its hostel area key (e.g. "mandakini") — the inverse
 * grouping used by the area-focus dim to decide whether a room the player stands
 * in belongs to a named building area.
 */
export function areaIdForRoom(roomId: string): string | undefined {
  return AREA_NAMES.find((a) => a.rooms?.includes(roomId))?.id;
}

/**
 * Full human-readable label for a private room, combining its hostel/area name
 * with the room number — e.g. "Mandakini Hostel · Room 1". Every UI surface that
 * shows a room to a player (entry toast, chat Room tab, knock/admin panels,
 * roster) resolves the name through here so the whole app agrees, and the
 * backend seed aligns `rooms.name` to the same string. Falls back to a bare
 * "Room <id>" for any id not grouped under an area (keeps callers total).
 */
export function roomDisplayName(roomId: string): string {
  const area = areaNameForRoom(roomId);
  return area ? `${area} · Room ${roomId}` : `Room ${roomId}`;
}

/**
 * Terminal outcome of a knock, delivered to the knocker (PRD 14). `canceled` is
 * client-initiated and never sent back, so it is not on the wire.
 */
export const KNOCK_RESULTS = ["approved", "denied", "timeout"] as const;

/** How adminship was conferred, carried on `admin-changed` (PRD 14). */
export const ADMIN_CHANGE_REASONS = ["initial", "succession"] as const;

/**
 * How long an unanswered knock waits before it auto-expires as denied (PRD 14).
 * The backend may shrink it via config for tests; behaviour is asserted through
 * the resulting `knock-result`, never this constant.
 */
export const KNOCK_TIMEOUT_MS = 30_000;

/**
 * Reasons a meeting-start countdown can be canceled: a seated player stood up,
 * an unseated player entered the room, or an occupant left and the all-seated
 * predicate no longer holds (e.g. the head-count dropped below 2).
 */
export const MEETING_CANCEL_REASONS = ["stand", "unseated-entry", "leave"] as const;

/**
 * Default length of the cancelable "Meeting starting…" countdown, in ms. The
 * backend may shrink it via config for tests; the wire payload always carries
 * the effective `durationMs`, so clients must read the payload, not this value.
 */
export const MEETING_COUNTDOWN_MS = 3000;

/**
 * Chat surfaces a typed cooldown notice can apply to (PRD 25.11). Chat is
 * rate-limited server-side; an excess send is refused with a `chat-cooldown`
 * carrying the surface so the right UI (ChatBox for world/room + whisper, the
 * meeting panel for meeting) shows the retry timing instead of dropping silently.
 * `world` covers both world and room lines — they share the ChatBox surface and
 * the same per-player limiter.
 */
export const CHAT_COOLDOWN_SCOPES = ["world", "whisper", "meeting"] as const;
export type ChatCooldownScope = (typeof CHAT_COOLDOWN_SCOPES)[number];

/** Client → server socket event names. */
export const CLIENT_EVENTS = {
  join: "join",
  move: "move",
  chat: "chat",
  whisper: "whisper",
  knock: "knock",
  cancelKnock: "cancel-knock",
  approveKnock: "approve-knock",
  denyKnock: "deny-knock",
  toggleAllowAll: "toggle-allow-all",
  roomLeave: "room-leave",
  seatSit: "seat-sit",
  seatStand: "seat-stand",
  meetingChat: "meeting-chat",
  boardSit: "board-sit",
  boardStand: "board-stand",
  boardAccept: "board-accept",
  boardMove: "board-move",
} as const;

/** Server → client socket event names. */
export const SERVER_EVENTS = {
  init: "init",
  playerJoined: "player-joined",
  playerMoved: "player-moved",
  playerLeft: "player-left",
  chat: "chat",
  whisper: "whisper",
  whisperFail: "whisper-fail",
  chatCooldown: "chat-cooldown",
  knockPending: "knock-pending",
  knockResult: "knock-result",
  adminChanged: "admin-changed",
  roomOpenState: "room-open-state",
  capacityAlert: "capacity-alert",
  seatUpdate: "seat-update",
  meetingCountdown: "meeting-countdown",
  meetingCountdownCanceled: "meeting-countdown-canceled",
  meetingStarted: "meeting-started",
  meetingEnded: "meeting-ended",
  meetingParticipantJoined: "meeting-participant-joined",
  meetingParticipantLeft: "meeting-participant-left",
  meetingChat: "meeting-chat",
  boardUpdate: "board-update",
  boardError: "board-error",
  presenceSnapshot: "presence-snapshot",
} as const;

/**
 * Every server → client event name, as a tuple. The frontend net layer subscribes
 * to exactly these, so keeping the list here prevents it from drifting out of sync
 * with the emitters.
 */
export const SERVER_EVENT_NAMES = [
  SERVER_EVENTS.init,
  SERVER_EVENTS.playerJoined,
  SERVER_EVENTS.playerMoved,
  SERVER_EVENTS.playerLeft,
  SERVER_EVENTS.chat,
  SERVER_EVENTS.whisper,
  SERVER_EVENTS.whisperFail,
  SERVER_EVENTS.chatCooldown,
  SERVER_EVENTS.knockPending,
  SERVER_EVENTS.knockResult,
  SERVER_EVENTS.adminChanged,
  SERVER_EVENTS.roomOpenState,
  SERVER_EVENTS.capacityAlert,
  SERVER_EVENTS.seatUpdate,
  SERVER_EVENTS.meetingCountdown,
  SERVER_EVENTS.meetingCountdownCanceled,
  SERVER_EVENTS.meetingStarted,
  SERVER_EVENTS.meetingEnded,
  SERVER_EVENTS.meetingParticipantJoined,
  SERVER_EVENTS.meetingParticipantLeft,
  SERVER_EVENTS.meetingChat,
  SERVER_EVENTS.boardUpdate,
  SERVER_EVENTS.boardError,
  SERVER_EVENTS.presenceSnapshot,
] as const;

/**
 * Server-observable activities a student can be in, for the social-arrival read
 * model (PRD 25.26). Every kind here is derived from authoritative server state:
 * `world` (free-roaming the campus), `room` (inside a private room), `meeting`
 * (a live meeting in that room), `board` (seated at a server-authoritative board
 * table), and `stage` (within the stage gathering zone). Arcade play is a
 * client-side overlay the server never observes, so it is deliberately absent —
 * the read model never reports an activity it cannot verify.
 */
export const PRESENCE_ACTIVITY_KINDS = ["world", "room", "meeting", "board", "stage"] as const;
export type PresenceActivityKind = (typeof PRESENCE_ACTIVITY_KINDS)[number];

/** Activity kinds that describe a joinable/active *space* (everything but the open world). */
export const ACTIVE_SPACE_KINDS = ["room", "meeting", "board", "stage"] as const;
export type ActiveSpaceKind = (typeof ACTIVE_SPACE_KINDS)[number];

/**
 * Size / bound limits enforced by the backend zod schemas and mirrored by the
 * frontend UI (e.g. the chat input cap). Single source of truth so a UI cap and a
 * server cap can never silently diverge.
 */
export const LIMITS = {
  /** Identifiers carried on the wire. */
  spaceIdMax: 64,
  roomIdMax: 64,
  /** Whisper target is a player id. */
  playerIdMax: 64,
  /** Chat / whisper message body. */
  chatTextMax: 500,
  whisperTextMax: 500,
  /** Server-side sanity ceiling for movement coordinates. */
  moveCoordMax: 100_000,
  /** Credentials. */
  usernameMin: 3,
  usernameMax: 32,
  passwordMin: 8,
  passwordMax: 128,
  /** LiveKit token request. */
  roomNameMax: 128,
  /** Client error beacon payload caps. */
  clientErrorMessageMax: 2000,
  clientErrorStackMax: 8000,
  clientErrorShaMax: 64,
  clientErrorUrlMax: 500,
  clientErrorUserAgentMax: 300,
  clientErrorContextMax: 200,
  /** Arcade high scores. */
  arcadeScoreMax: 10_000_000,
  /** Rows returned in a per-game leaderboard. */
  arcadeLeaderboardMax: 10,
  /** Board-game seat index (two seats per table: 0 and 1). */
  boardSeatMax: 1,
  /** Sanity ceiling on a board move index (Connect-4 has 7 cols, TTT 9 cells). */
  boardMoveIndexMax: 41,
  /** Social-arrival read model (PRD 25.26): bounds on a presence snapshot. */
  presenceMaxPeople: 500,
  presenceMaxSpaces: 200,
  presencePlaceLabelMax: 80,
  /** Pilot schedule config entries (versioned, backend-deployed). */
  scheduleTitleMax: 80,
  scheduleDescriptionMax: 200,
  scheduleMaxEntries: 100,
} as const;

/** Allowed username characters (lowercase alphanumerics, dash, underscore). */
export const USERNAME_PATTERN = /^[a-z0-9_-]+$/;

/**
 * Rate-limit windows and other timing constants enforced server-side. Kept here so
 * the magic numbers behind the contract's abuse protections live in one place.
 */
export const RATE_LIMITS = {
  /** World / room chat messages per player per window (anti-spam; PRD 25.11). */
  chatLimit: 10,
  chatWindowSeconds: 10,
  /** Whispers per player per window. */
  whisperLimit: 20,
  whisperWindowSeconds: 60,
  /** In-meeting chat messages per player per window (PRD 10). */
  meetingChatLimit: 20,
  meetingChatWindowSeconds: 60,
  /** Knock attempts per player+room per window (anti-harassment; PRD 14). */
  knockLimit: 5,
  knockWindowSeconds: 60,
  /** Auth (signup/signin) REST limiter. */
  authWindowMs: 15 * 60_000,
  authLimit: 40,
  /** Client-error beacon sink limiter (per IP). */
  clientErrorWindowMs: 60_000,
  clientErrorLimit: 10,
  /** Authenticated product-analytics ingestion limiter (per student). */
  analyticsWindowMs: 60_000,
  analyticsLimit: 120,
  /** Arcade high-score submit limiter (per IP). */
  arcadeScoreWindowMs: 60_000,
  arcadeScoreLimit: 30,
  /** Arcade leaderboard read limiter (per IP). */
  arcadeLeaderboardWindowMs: 60_000,
  arcadeLeaderboardLimit: 120,
  /** Minimum spacing between accepted `move` events from one socket. */
  moveThrottleMs: 40,
} as const;
